# yaml-language-server: $schema=https://json.schemastore.org/dart-build.json
targets:
  $default:
    builders:
      json_serializable:
        options:
          # defaults shown
          # Docs: https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable-class.html
          any_map: false
          checked: false
          constructor: ""
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true # default: false
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true
