name: andax
description: Interactive branching narratives.
publish_to: "none"
version: 1.0.2+10

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.10.2
  cloud_firestore: ^3.1.1
  firebase_storage: ^10.2.0
  url_launcher: ^6.0.17
  shared_preferences: ^2.0.9
  firebase_auth: ^3.3.0
  google_sign_in: ^5.2.1
  algolia: ^1.0.1
  flutter_markdown: ^0.6.3
  enum_to_string: ^2.0.1
  dotted_border: ^2.0.0+1
  simple_animations: ^4.0.1
  uuid: ^3.0.5
  provider: ^6.0.1
  infinite_scroll_pagination: ^3.1.0
  flutter_xlider:
    git: https://github.com/Ali-Azmoud/flutter_xlider.git
  sign_in_with_apple: ^3.3.0
  crypto: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_lints: ^1.0.4

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
