// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3dbf73ochJL2Fa2vs6lU0Km6wxKR61h8',
    appId: '1:803265650064:web:1d3c96ffa35ab2477e6715',
    messagingSenderId: '803265650064',
    projectId: 'andaxapp',
    authDomain: 'andaxapp.firebaseapp.com',
    storageBucket: 'andaxapp.appspot.com',
    measurementId: 'G-9PHF21CBLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrbKDNMQ8Lsx2sJCJd9wJdZttqswDCOGs',
    appId: '1:803265650064:android:ab87bac26869951a7e6715',
    messagingSenderId: '803265650064',
    projectId: 'andaxapp',
    storageBucket: 'andaxapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsIEymP95dMDwUcRQn9DS5aUHqzPdhOEg',
    appId: '1:803265650064:ios:7e58ead8080b848a7e6715',
    messagingSenderId: '803265650064',
    projectId: 'andaxapp',
    storageBucket: 'andaxapp.appspot.com',
    androidClientId:
        '803265650064-29skmosa9nprali9fmlv7so2s53tgimt.apps.googleusercontent.com',
    iosClientId:
        '803265650064-rkqeijtivvk9vujfaaev705bcgvqijq8.apps.googleusercontent.com',
    iosBundleId: 'com.alkaitagi.andax',
  );
}
